version: '3'

services:
  nginx:
      image: nginx:stable
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - "./conf.d:/etc/nginx/conf.d"
      links:
        - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/web
      - /web/node_modules
