export const ActionTypes = {
  REQUEST_POST_SIGN_IN: '@user/REQUEST_POST_SIGN_IN',
  SUCCESS_POST_SIGN_IN: '@user/SUCCESS_POST_SIGN_IN',
  FAILURE_POST_SIGN_IN: '@user/FAILURE_POST_SIGN_IN'
} as const
